# These are supported funding model platforms

github: ry-ops # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: ry-ops # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: ry-ops # Replace with a single Ko-fi username
tidelift: ry-ops # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: ry-ops # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: ry-ops # Replace with a single Liberapay username
issuehunt: ry-ops # Replace with a single IssueHunt username
lfx_crowdfunding: ry-ops # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: ry-ops # Replace with a single Polar username
buy_me_a_coffee: ry-ops # Replace with a single Buy Me a Coffee username
thanks_dev: ry-ops # Replace with a single thanks.dev username
